### ISSUE TITLE
Add link to Manual.pdf to README.md

### ISSUE THREAD

**Issue by tseemann** [phac-nml/neptune#2]
Eric,

It took me a while to figure out that the documentation was in a Latex PDF here:

https://github.com/phac-nml/neptune/blob/release/1.2/documentation/manual/Manual.pdf

Can you link to it from README.md or even better somehow get it in Markdown format?

Torst

**Comment by fbristow** [comment]
Hi Eric,

If you're planning to re-write your docs in Markdown (or whatever) instead of just linking to your latex document, you can try using [pandoc](http://pandoc.org/) to get started. That should make it a lot easier to translate between latex and Markdown (or whatever).

**Comment by emarinier** [comment]
I've made simple Markdown links in the README that direct to the manual. I'm planning a patch release in the very near future to help clarify the manual. The documentation being linked to will be the PDF manual, not the Latex document.

There are currently no plans to rewrite the documentation in another format. However, this might change in the future.

**Comment by emarinier** [comment]
I've added simple Markdown links in the README that link directly to the PDF manual. This should help direct users to the documentation.

Release: 1.2.4
Merge: 48b1ab5f06ad8dd1f92fb5aec9d136c9326bc553

**Comment by emarinier** [comment]
Actually, I've changed my mind after reading:

http://hdl.handle.net/1807/73111

and converted the documentation into a website hosted on GitHub Pages:

https://phac-nml.github.io/neptune/

I'm working on polishing everything up now.
