### ISSUE TITLE
CFastaReader: Hyphens are invalid and will be ignored around line XX

### ISSUE THREAD

**Issue by nbawe** [phac-nml/neptune#5]
Hello, I get following error, should I remove all gaps before analysis:

```
neptune --inclusion inclusion --exclusion exclusion --output output --kmer 100 
Neptune v1.2.5

k-mer Counting...
Submitted 216 jobs.
0.228509 seconds

k-mer Aggregation...
Submitted 65 jobs.
0.189835 seconds

Signature Extraction...
Submitted 4 jobs.
0.007363 seconds

Signature Filtering...
Submitted 2 jobs.
Submitted 4 jobs.
CFastaReader: Hyphens are invalid and will be ignored around line 2
CFastaReader: Hyphens are invalid and will be ignored around line 2
CFastaReader: Hyphens are invalid and will be ignored around line 2
CFastaReader: Hyphens are invalid and will be ignored around line 2
CFastaReader: Hyphens are invalid and will be ignored around line 4
CFastaReader: Hyphens are invalid and will be ignored around line 4
Warning: [blastn] Query is Empty!
Warning: [blastn] Query is Empty!
Warning: [blastn] Query is Empty!
Warning: [blastn] Query is Empty!
0.319875 seconds

NOTICE: No signatures were identified.

Complete!
```

**Comment by emarinier** [comment]
It looks like the warnings are a consequence of CFasterReader (which I understand is being used by BLAST) and BLASTn. Neptune works best when the data contains only A, C, G, and T characters, but it can work around the other IUPAC nucleotide code characters when they occur infrequently. I suspect the final steps with BLASTn are having trouble with gaps represented by hyphens.

I would recommend removing the hyphen characters, if possible, and it should hopefully clear up the problem.

**Comment by nbawe** [comment]
Ok thanks!

**Comment by nbawe** [comment]
Does neptune allow the use of draft genomes (contig) fasta files?

**Comment by emarinier** [comment]
Yup, the intended input of Neptune is FASTA files. These can be from draft genome assemblies with multiple contigs.

**Comment by nbawe** [comment]
Thanks!

Is there option for more that two group comparison. As I understand right now inclusion (is all sequences from one type) and exclusion (all the other/other type(s)). So by default neptune finds k-mers in inclusion and not exclusion but compares inclusion k-mers with exclusion sequences?

 Also how to cite neptune?

**Comment by nbawe** [comment]
Ok - found citation and also answer from publication. It compares two groups.

**Comment by emarinier** [comment]
That's correct. It only compares two groups. The only thing I'd add is that it locates sequences much longer (usually) than k-mers by using the k-mer information from the two groups.

The paper to cite would be this one: https://academic.oup.com/nar/article/45/18/e159/4083563

**Comment by nbawe** [comment]
Removed gaps still get Warning: [blastn] Query is Empty!
